//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordReplacerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordReplacerApp.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string addFiles {
            get {
                return ResourceManager.GetString("addFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addReplace {
            get {
                return ResourceManager.GetString("addReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        public static string changeFolder {
            get {
                return ResourceManager.GetString("changeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string removeAllFiles {
            get {
                return ResourceManager.GetString("removeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string removeReplace {
            get {
                return ResourceManager.GetString("removeReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        public static string removeSelectedFile {
            get {
                return ResourceManager.GetString("removeSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace date.
        /// </summary>
        public static string replaceDate {
            get {
                return ResourceManager.GetString("replaceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to:.
        /// </summary>
        public static string replaceDateTo {
            get {
                return ResourceManager.GetString("replaceDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder:.
        /// </summary>
        public static string saveFolder {
            get {
                return ResourceManager.GetString("saveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace from:.
        /// </summary>
        public static string textFrom {
            get {
                return ResourceManager.GetString("textFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace to:.
        /// </summary>
        public static string textTo {
            get {
                return ResourceManager.GetString("textTo", resourceCulture);
            }
        }
    }
}
